language: ruby
cache:
  bundler: true

rvm:
  - 2.0.0

notifications:
  email: false

bundler_args: "--without development"

before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database esm_test;' -U postgres
  - RAILS_ENV=test bundle exec rake db:migrate db:test:prepare

script:
  - bundle exec rake code_analysis
